apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    name: frontend
    environment: dev
    project: expense
    component: frontend
  ports:
  - protocol: TCP
    port: 80 #serviceport differs from target port
    targetPort: 80
