apiVersion: v1
kind: Service
metadata:
  name: service-LB
spec:
  type: LoadBalancer
  selector:
    name: frontend
    environment: dev
    project: expense
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 32760
